theme: minima

build:
  publicUrl: /saber-template-rin/

siteConfig:
  title: Love Rin
  url: https://lubien.me/saber-template-rin/
  author: Tohsaka Rin
  email: tohsaka@tohsaka.moe
  description: Behold the best

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    twitter: joao_lubien
    github: lubien
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
